#!/bin/bash
#
# Install web services to a target file system.
#

target=$1

if [ -z "${target}" -o ! -d "${target}" ]; then
  echo "Error: Must provide the full path to target filesystem"
  exit 1
fi

# copy NGINX configuration
cp -rp /etc/nginx/conf.d/default.conf "${target}"/etc/nginx/conf.d/default.conf

# copy sample web services
cp -rp /vagrant/services "${target}"/opt/.

# initial start up script for Docker
tee -a "${target}"/opt/startapp << END
#!/bin/bash

# turn on bash's job control
set -m

echo "Starting RabbitMQ"
/sbin/rabbitmq-server &
echo "Starting couchdb"
/opt/couchdb/bin/couchdb &
echo "Starting NGINX"
/sbin/nginx

echo "Restarting backend service: time"
/bin/node /opt/services/time/server.js &

echo "Restarting backend service: random"
/bin/node /opt/services/random/server.js &

# the primary process is rabbitmq and bring it to the foreground, leaving it there
# indefinitely
fg %1
END
chmod 755 "${target}"/opt/startapp
chown root:root -Rf "${target}"/opt/*
