# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "geerlingguy/centos7"
  config.vm.define "docker"
  config.vm.hostname = "docker"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "docker"
    vb.memory = 1024
    vb.cpus = 1
  end

  # NGINX will be running on port 3000 on the guest. This will be the reverse
  # proxy into all the backend services deployed on the guest.
  config.vm.network "forwarded_port", host: 8000, guest: 3000

  # Used for direct access to backend services
  config.vm.network "forwarded_port", host: 5000, guest: 9000
  config.vm.network "forwarded_port", host: 5001, guest: 9001
  # rabbitmq
  config.vm.network "forwarded_port", host: 5002, guest: 15672
  # couchdb
  config.vm.network "forwarded_port", host: 5003, guest: 5984


  # Update new software/cots as needed rather than rebuilding the box image.
  config.vm.provision "docker", type: "shell", inline: <<-SHELL
    yum install -y docker
    systemctl start docker
    systemctl enable docker

    if [ -f "/vagrant/g7dev.tar" ]; then
      echo "Importing /vagrant/g7dev.tar Docker image"
      docker import /vagrant/g7dev.tar g7dev:latest
    fi

    # docker image build -t bulletinboard:1.1 .
    # docker run -it -d g7dev  /bin/bash
    # docker run -it -d g7dev /bin/bash /opt/startapp
  SHELL

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
